#!/bin/bash
# tools/jwt_tool/install.sh — version pin, install, and verification for jwt_tool.
set -eux -o pipefail

. /tmp/tool-install-helpers.sh

JWT_TOOL_VERSION=2.3.0
JWT_TOOL_SHA256=0f8c32aa9f67cea4312e5df81d48f72dc5daf57f3cc0ce09d67db78e23fbe451
JWT_TOOL_VENV=/opt/venvs/jwt-tool

# jwt_tool is a single script plus its own directory of wordlists, run from
# where it sits. It is NOT on PyPI.
fetch "https://github.com/ticarpi/jwt_tool/archive/refs/tags/v${JWT_TOOL_VERSION}.tar.gz" \
    "$JWT_TOOL_SHA256" /tmp/jwt_tool.tar.gz
tar -xzf /tmp/jwt_tool.tar.gz -C /opt
mv "/opt/jwt_tool-${JWT_TOOL_VERSION}" /opt/jwt_tool
chmod +x /opt/jwt_tool/jwt_tool.py
rm -f /tmp/jwt_tool.tar.gz

# Dependencies come from the script's imports, not from upstream's
# requirements.txt: that file lists `cprint`, which is not a module jwt_tool
# imports (it uses termcolor's cprint) and which on PyPI resolves to an
# unrelated "Printing and debugging with color" package. Installing the real
# four keeps the venv honest.
python3 -m venv "$JWT_TOOL_VENV"
"$JWT_TOOL_VENV/bin/pip" install --no-cache-dir --upgrade pip
"$JWT_TOOL_VENV/bin/pip" install --no-cache-dir \
    termcolor pycryptodomex requests ratelimit

"$JWT_TOOL_VENV/bin/python3" -m pip check

# The script writes jwtconf.ini and generated keys into its working directory,
# so it is launched through a wrapper that owns that directory rather than
# being symlinked onto PATH directly.
cat > /usr/local/bin/jwt_tool <<'WRAPPER'
#!/bin/sh
# Generated by tools/jwt_tool/install.sh.
# jwtconf.ini, jwt-common.txt and any keys the tool generates live in
# /opt/jwt_tool, which is where the tool expects to find its own data files.
cd /opt/jwt_tool || exit 1
exec /opt/venvs/jwt-tool/bin/python3 /opt/jwt_tool/jwt_tool.py "$@"
WRAPPER
chmod +x /usr/local/bin/jwt_tool

# Parse the entry point: a syntax error in a vendored tree would otherwise
# surface only when the tool first runs against a target.
/opt/venvs/jwt-tool/bin/python3 -c "import ast; ast.parse(open('/opt/jwt_tool/jwt_tool.py').read())"

# -h needs no token (it is an optional positional), and prints without
# touching the config. Verified against v2.3.0.
verify_output 'jwt_tool' jwt_tool -h
