#!/bin/bash
# tools/graphql-cop/install.sh — version pin, install, and verification for graphql-cop.
set -eux -o pipefail

. /tmp/tool-install-helpers.sh

GRAPHQL_COP_TAG=1.16
GRAPHQL_COP_SHA256=56b201ce7fb81baa5a7ba4e562be27914267174ca70813f60af06a3d81811d9a
GRAPHQL_COP_VENV=/opt/venvs/graphql-cop

# Not on PyPI, and a script rather than a package: it runs from its own tree,
# which also carries the static assets its banner uses.
fetch "https://github.com/dolevf/graphql-cop/archive/refs/tags/${GRAPHQL_COP_TAG}.tar.gz" \
    "$GRAPHQL_COP_SHA256" /tmp/graphql-cop.tar.gz
tar -xzf /tmp/graphql-cop.tar.gz -C /opt
mv "/opt/graphql-cop-${GRAPHQL_COP_TAG}" /opt/graphql-cop
chmod +x /opt/graphql-cop/graphql-cop.py
rm -f /tmp/graphql-cop.tar.gz

# Upstream's requirements.txt pins requests==2.25.1 and PySocks==1.7.1 from
# 2021. The scanner calls a small, stable part of requests; taking the 2021
# pins would force a five-year-old urllib3 into this venv for no benefit.
python3 -m venv "$GRAPHQL_COP_VENV"
"$GRAPHQL_COP_VENV/bin/pip" install --no-cache-dir --upgrade pip
"$GRAPHQL_COP_VENV/bin/pip" install --no-cache-dir \
    requests simplejson termcolor PySocks

"$GRAPHQL_COP_VENV/bin/python3" -m pip check

cat > /usr/local/bin/graphql-cop <<'WRAPPER'
#!/bin/sh
# Generated by tools/graphql-cop/install.sh: the script resolves its own
# directory for assets, so run it from there.
cd /opt/graphql-cop || exit 1
exec /opt/venvs/graphql-cop/bin/python3 /opt/graphql-cop/graphql-cop.py "$@"
WRAPPER
chmod +x /usr/local/bin/graphql-cop

/opt/venvs/graphql-cop/bin/python3 -c "import ast; ast.parse(open('/opt/graphql-cop/graphql-cop.py').read())"

# -h prints usage without contacting a target.
verify_output 'graphql-cop' graphql-cop -h
